In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Define the vocabulary size
voc_size = 10000

In [5]:
### One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[9628, 1890, 3279, 8949],
 [9628, 1890, 3279, 3709],
 [9628, 1845, 3279, 2491],
 [115, 1697, 7611, 9692, 3090],
 [115, 1697, 7611, 9692, 712],
 [366, 9628, 4989, 3279, 523],
 [5692, 4278, 3704, 9692]]

In [8]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9628 1890 3279 8949]
 [   0    0    0    0 9628 1890 3279 3709]
 [   0    0    0    0 9628 1845 3279 2491]
 [   0    0    0  115 1697 7611 9692 3090]
 [   0    0    0  115 1697 7611 9692  712]
 [   0    0    0  366 9628 4989 3279  523]
 [   0    0    0    0 5692 4278 3704 9692]]


In [10]:
## Feature Representation
dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[[ 0.04631427,  0.01953535, -0.0459276 ,  0.04301536,
          0.00729958, -0.00797691,  0.03222624,  0.03192499,
          0.04891009, -0.04859244],
        [ 0.04631427,  0.01953535, -0.0459276 ,  0.04301536,
          0.00729958, -0.00797691,  0.03222624,  0.03192499,
          0.04891009, -0.04859244],
        [ 0.04631427,  0.01953535, -0.0459276 ,  0.04301536,
          0.00729958, -0.00797691,  0.03222624,  0.03192499,
          0.04891009, -0.04859244],
        [ 0.04631427,  0.01953535, -0.0459276 ,  0.04301536,
          0.00729958, -0.00797691,  0.03222624,  0.03192499,
          0.04891009, -0.04859244],
        [-0.00596173,  0.02415821,  0.03722611,  0.0488959 ,
          0.02708064,  0.03208711, -0.04189736,  0.02275032,
          0.00996138, -0.03453767],
        [-0.03165241, -0.00815756,  0.02787716, -0.00652253,
         -0.01760721, -0.02952956,  0.01991501,  0.04914217,
          0.0195743 , -0.04559853],
        [-0.04560978, -0.02789894,  0.01651355, -0.0